# Generated by Django 5.1.3 on 2024-11-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.AddField(
            model_name='review',
            name='customer_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя Клиента'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_photo',
            field=models.ImageField(null=True, upload_to='uploads/customer_photo/', verbose_name='Фото Клиента'),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
