# Generated by Django 5.1.3 on 2024-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer_photo',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(default=5, max_length=50, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
