# Generated by Django 5.1.3 on 2024-12-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_review_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.CharField(default=123, max_length=10, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
